[workspace]
resolver = "3"
members = ["tracer-core"]

[workspace.dependencies]
dhat = "0.3.3"
glam = "0.31.0"
range2d = "0.2.0"
sdl2 = "0.38.0"

[profile.dev]
debug = true
strip = false
lto = true
codegen-units = 1
panic = "abort"
split-debuginfo = "off"

