[package]
name = "tracer-render"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true }
rayon = { workspace = true }
sdl2 = { workspace = true }
tracer-core = { path = "../tracer-core" }

[features]
dhat-heap = []
hyperfine = []
