[package]
name = "tracer-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dhat = { workspace = true }
glam = { workspace = true }
range2d = { workspace = true }
rayon = { workspace = true }
sdl2 = { workspace = true }

[features]
dhat-heap = []
hyperfine = []
